name: ObservePoint Audit

description:
  Starts ObservePoint audits and checks for successful start.

inputs:
  audit_ids:
    description: 'Comma-separated list of audit IDs to start.'
    required: true
  op_api_key:
    description: 'API key for ObservePoint.'
    required: true

runs:
  using: 'composite'
  steps:
    - id: set-outputs
      name: ObservePoint Audit
      shell: bash
      run: |
        audit_ids_string="${{ inputs.audit_ids }}"
        audit_ids=(${audit_ids_string//,/ })
        fail_flag=0
        for audit_id in "${audit_ids[@]}"
        do
        response=$(curl -s -w "%{http_code}" -o response.json "https://app.observepointstaging.com/api/v2/web-audits/${audit_id}/runs" \
          -H "authorization: api_key ${{ inputs.op_api_key }}" \
          --data-raw '{}')
        http_code="${response: -3}"
        response_body=$(<response.json)
        
        if [[ "$http_code" =~ ^[45] ]]; then
          echo "Failed request for Audit ID: $audit_id with HTTP Status: $http_code"
          echo "Response Body:"
          cat response.json
          echo "------"
          fail_flag=1
        fi
        done
        
        if [ $fail_flag -eq 1 ]; then
        echo "One or more audits failed to start correctly."
        exit 1
        fi
