# main.yml

name: Call ObservePoint Audit

on:
  push:
    branches:
      - main

# Grant permission to dispatch other workflows
permissions:
  contents: read              # to check out your code
  actions: write              # to trigger workflow_dispatch
  pull-requests: write        # if you ever comment on PRs

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: sleep 2

  test:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Test
        run: sleep 2

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Deploy
        run: sleep 2

  run_observepoint_audits:
    name: Run ObservePoint Audits
    runs-on: ubuntu-latest
    needs:
      - deploy
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Start ObservePoint audits
        uses: ./.github/actions/run_op_audit
        with:
          audit_ids:   '230171'
          op_api_key:  ${{ secrets.OP_API_KEY }}
          # point at the callback workflow you’ve created:
          callback_url:   https://api.github.com/repos/${{ github.repository }}/actions/workflows/audit-complete.yml/dispatches
          # use the built-in token to authorize that dispatch
          callback_token: ${{ secrets.GITHUB_TOKEN }}
          # if you’re on a PR you can pull in ${{ github.event.pull_request.number }},
          # but on a plain push you can omit pr_number and update your action to make it optional.
          pr_number:      ${{ github.event.pull_request.number || '' }}
          # commit SHA for setting status
          commit_sha:     ${{ github.sha }}
