name: Call ObservePoint Audit

on:
  push:
    branches:
      - main

jobs:
  call_audit_workflow:
    uses: ./.github/workflows/observepoint_audit.yml@run_audit
    with:
      audit_ids: '335161'
      op_api_key: ${{ secrets.OP_API_KEY }}
