name: Call ObservePoint Audit

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: sleep 120

  test:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Test
        run: sleep 200

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Deploy
        run: sleep 180

  run_observepoint_audits:
    name: Run ObservePoint Audits
    runs-on: ubuntu-latest
    needs:
      - deploy
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Start ObservePoint audits
        uses: ./.github/actions/run_op_audit
        with:
          audit_ids: '335161'
          op_api_key: ${{ secrets.OP_API_KEY }}

