name: Call ObservePoint Audit

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building the app"

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Testing the app"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying the app"

  run_observepoint_audits:
    name: Run ObservePoint Audits
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Start ObservePoint audits
        uses: ./.github/actions/run_op_audit
        with:
          audit_ids: '335161'
          op_api_key: ${{ secrets.OP_API_KEY }}
