name: Call ObservePoint Audit

on:
  push:
    branches:
      - main

jobs:
  call_audit_workflow:
    uses: ./observepoint_audit.yml
    with:
      audit_ids: '335161'
      op_api_key: ${{ secrets.OP_API_KEY }}
