name: Call ObservePoint Audit

on:
  push:
    branches:
      - main

jobs:
  demo_job:
    runs-on: ubuntu-latest
    steps:
      - name: Use local hello-world-action
        uses: ./.github/actions/run_op_audit
        with:
          audit_ids: '335161'
          op_api_key: ${{ secrets.OP_API_KEY }}