name: ObservePoint Audit

on:
  workflow_call:
    inputs:
      audit_ids:
        type: string
        required: true
        description: 'Comma-separated list of audit IDs'
      op_api_key:
        type: string
        required: true
        description: 'ObservePoint API Key'

jobs:
  run_audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Perform Audits
        run: |
          audit_ids_string="${{ inputs.audit_ids }}"
          audit_ids=(${audit_ids_string//,/ })
          fail_flag=0
          for audit_id in "${audit_ids[@]}"
          do
            response=$(curl -s -w "%{http_code}" -o response.json "https://app.observepointstaging.com/api/v2/web-audits/${audit_id}/runs" \
              -H "authorization: api_key ${{ inputs.op_api_key }}" \
              --data-raw '{}')
            http_code="${response: -3}"
            response_body=$(<response.json)

            if [[ "$http_code" =~ ^[45] ]]; then
              echo "Failed request for Audit ID: $audit_id with HTTP Status: $http_code"
              echo "Response Body:"
              cat response.json
              echo "------"
              fail_flag=1
            fi
          done

          if [ $fail_flag -eq 1 ]; then
            echo "One or more audits failed to start correctly."
            exit 1
          fi
